language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

install:
- pip install .

script: pytest

deploy:
  provider: pypi
  user: kchen
  password:
    secure: oM9oqjr5MoGbuk/25F9V8baSfs8YVPWo6r4SV6BhWy76J7kUAjrQNUkM3MYdz0IZ6kmj7YpfDQ/Z4LYsvUA9uvsdZ/DmXf7t09dU7VMZMYkPtthmFwz2/xkSvvgbUMbHgPfjcmscqkLNlLxRJbNGk1wDNnskg4QIr0CvMKmpgKa/6qvabnLdNkBX+CH8AejyvK/z/Cx21oB6EV+OgKIoNFhkvxUyeOXCWTqwfLY/wwP7uly06IE7b2kNU9qexT3ycbeRqdRkwTa5OYShWLlQxJBPEyeT+LEQlqEHzdbxBuSXBGdxt5LS/AW66krqMtwZ5Mf10hHR1DUUg4QrZoAIq0kWQ/W/b8TAmwEPAiJqRzTIUBSvFEreLjSFy3rkPhx32D3DW6M6zbyRnn7louJn1P74VXhCTDUJHRzYn+3YovAdAD04Vo7d1lmtNXIX1hCJ4CskPEdEd++GZkFkunxIr4yLzXe5mSCPdmqYGM8C0Mjt16BakAOklalBfPTlfsR8FvUEhRuwCZ8vK9HQ236jODKZcfXCYyhgLPg5J7RE/qiERCIjdxDAXIKaX6IGaNgAPQaG+65bdVUtAK8S/SCRcYlklr0+0zeINbRB3rHGViMWKHkgFpUkZY0Mv3tZA1wdR97CHjtnfxnIOf3ImJnjspOzC99EzBMh/SMhKmJ8OuM=
  on:
    branch: master
    tags: true
    python: '3.7'
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
